name: Test Python
on: push

concurrency:
  group: CI-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  python-tests:
    continue-on-error: false
    strategy:
      max-parallel: 10
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12']
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install packages
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git xvfb

      - name: Python Setup
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r detection/requirements.txt
          pip install pytest

      - name: Run Tests
        run: pytest
